package en.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseNews<M extends BaseNews<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setHeadline(java.lang.String headline) {
		set("headline", headline);
		return (M)this;
	}

	public java.lang.String getHeadline() {
		return get("headline");
	}

	public M setImgsrc(java.lang.String imgsrc) {
		set("imgsrc", imgsrc);
		return (M)this;
	}

	public java.lang.String getImgsrc() {
		return get("imgsrc");
	}

	public M setText(java.lang.String text) {
		set("text", text);
		return (M)this;
	}

	public java.lang.String getText() {
		return get("text");
	}

}
