package en.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_news", "id", News.class);
		arp.addMapping("t_reply", "id", Reply.class);
		arp.addMapping("t_slider", "id", Slider.class);
		arp.addMapping("t_theme", "id", Theme.class);
		arp.addMapping("t_user", "id", User.class);
	}
}

