package en.model;

import en.model.base.BaseSlider;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Slider extends BaseSlider<Slider> {
	public static final Slider dao = new Slider().dao();
}
